### ISSUE TITLE
Dependencies are not clear

### ISSUE THREAD

**Issue by akashdhruv** [HPCForge/BubbleML#1]
It would be good to have a requirements.txt file that one can `pip install` for dependencies. The conda command is not working for me, and I would like to setup my environment from scratch. Is this possible?

**Comment by akashdhruv** [comment]
`conda create -n bubble-sciml -f conda/bubbleml-pytorch-2.0.1-cuda-11.7.yaml
Collecting package metadata (current_repodata.json): done
Solving environment: unsuccessful attempt using repodata from current_repodata.json, retrying with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: failed

PackagesNotFoundError: The following packages are not available from current channels:

  - conda/bubbleml-pytorch-2.0.1-cuda-11.7.yaml

Current channels:

  - https://repo.anaconda.com/pkgs/main/linux-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/r/linux-64
  - https://repo.anaconda.com/pkgs/r/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.`

**Comment by akashdhruv** [comment]
Getting following error when I run: `conda create -n bubble-sciml -f conda/bubbleml-pytorch-2.0.1-cuda-11.7.yaml`

```
conda create -n bubble-sciml -f conda/bubbleml-pytorch-2.0.1-cuda-11.7.yaml
Collecting package metadata (current_repodata.json): done
Solving environment: unsuccessful attempt using repodata from current_repodata.json, retrying with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: failed

PackagesNotFoundError: The following packages are not available from current channels:

  - conda/bubbleml-pytorch-2.0.1-cuda-11.7.yaml

Current channels:

  - https://repo.anaconda.com/pkgs/main/linux-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/r/linux-64
  - https://repo.anaconda.com/pkgs/r/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.
```

**Comment by arthurfeeney** [comment]
Hi Akash, sorry for the error...  The correct command is  `conda env -n <name> create -f conda/pytorch-2.0.1-cuda-11.7.yaml`.  (remove the bubbleml- from the yaml file name.)

anaconda is the recommended package manager for pytorch. The conda env file functions similar to a requirements.txt. I can add a requirements.txt, but I think it would somewhat redundant.

**Comment by arthurfeeney** [comment]
I just updated the README. Thanks for pointing this out! Feel free to reopen if there's still issues.

I'm surprised your the first person to bring this up. It's definitely a mistake on my end, but several summer undergrads have setup their environment as well. I'll have to pester them to figure out how they did the setup :-)
