### ISSUE TITLE
Nucleation Model

### ISSUE THREAD

**Issue by arthurfeeney** [HPCForge/BubbleML#13]
The Flash-X simulations use a [simple nucleation model](https://github.com/Flash-X/Flash-X/blob/1b69b210183119acce8c0c4f406df56d78ae482f/source/physics/sourceTerms/Heater/HeaterMain/htr_lsReInitBlk.F90#L64-L65) to determine when bubbles form. In the existing experiments, we do not have access to this information. The process is something like "for a given nucleation site, if it has not been covered by vapor in the last 4 time units, form a new bubble."
Since it's so simple, we should just provide an implementation of it on our end.  This will just enables us to know where bubbles might be formed in future timesteps.

The nucleation sites are fixed throughout a simulation, but are initialized randomly(-ish). The density just needs to match approximately what is expected. The exact locations depend on factors that are essentially impossible to model, like micro-fissures in the heater surface. 

We should be able to match the randomized nucleation sites between the simulation and ML model. Or, just have the simulation output the precise nucleation sites.

**Comment by shakeel-hassan** [comment]
Algorithm needs a bit of improvement. working on it.
