### ISSUE TITLE
Inquiry on Reproducing Results from Table 10 in the Paper

### ISSUE THREAD

**Issue by leemingo** [HPCForge/BubbleML#18]
Firstly, I would like to express my gratitude for sharing your valuable research along with the code and dataset. It has been immensely helpful.

I am currently conducting experiments on PB-Saturated using the pb_temp.yaml file from the conf/paper/unet_arena directory, as per your environment setup. However, I am facing issues with replicating the results stated in Table 10 of your paper, where the Best RMSE for Unet_arena (UNet_mod) is listed as 0.035. Contrarily, when running the code, the highest result I achieve is an RMSE of 0.080 at Epoch 7.

I executed the `python sciml/train.py` using the pb_temp.yaml file located in conf/paper/unet_arena and the PB_WallSuperHeat.yaml from the conf/dataset directory.

Could you please guide me if there might be any steps or configurations I might have overlooked or if additional modifications are necessary to align with the published results?

Thank you for your attention and assistance.

**Comment by arthurfeeney** [comment]
Hi thank you for trying out our dataset.  Hmm, there should not be a need for you to make additional modifications.  My goal was that everything would "just work" as provided.
Two questions:
1. Have you tried running any of the checkpoints in our [model zoo](https://github.com/HPCForge/BubbleML/tree/main/model-zoo#sciml-models)? Do you get the same results as our paper with any of them?  I double checked the checkpoints before the conference and they matched what we list in the paper.
2. Do you mean you trained for 7 epochs and stopped, or that the error stopped improving after 7 epochs? As I recall, it took a little while for the results to be "good." I trained it for 250 epochs.

**Comment by leemingo** [comment]
Thanks for your response.

1. Yes, I tried using the checkpoints you provided in the repo, and I observed a similar result as noted in the table, with RMSE of 0.038. 
2. I also trained 250 epochs to reproduce the result, but the error stopped improving after 7 epochs. It seems that the unet_bench works well, suggesting that the issue might be with the execution of unet_mod. Could you suggest any other methods to verify or troubleshoot this?

Additionally, I conducted experiments on the PB-Subcooled dataset after working with the PB-Saturated data, and as indicated in the attached image file, there seems to be a slight discrepancy in RMSE compared to the scale in Table 9. I would appreciate any insights or suggestions you might have regarding this matter.

<img width="511" alt="image" src="https://github.com/HPCForge/BubbleML/assets/62419346/177c3164-efab-4e74-9eb5-8a8e951eb9e5">
<img width="503" alt="image" src="https://github.com/HPCForge/BubbleML/assets/62419346/a40f5975-1381-4699-b85a-04acc87c531b">

**Comment by leemingo** [comment]
Hi, I think there was some issue in my working environment.
I fixed the issue and it seems working well.
Thanks for your kind response.

**Comment by arthurfeeney** [comment]
great! thank you for letting me know it's working 👍
If you have any other problems, feel free to reopen this.
